# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  ENV.fetch('SIZE', 2).to_i.times {|i|
    config.vm.define "n#{i}" do |node|
      ip, name = "172.20.20.#{10 + i}", "app#{i}"
      node.vm.network "private_network", ip: ip
      node.vm.network "forwarded_port", guest: 7373, host: 17373 + i
      node.vm.provision "shell" do |s|
        s.path = "provision-app.sh"
        s.args = "#{ip} #{name}"
      end

      node.vm.provision 'shell' do |s|
        s.inline = <<-EOF
          sudo apt-get install cowsay -y && ln -s /usr/games/cowsay /usr/bin/cowsay && echo $1 | cowsay
        EOF
        s.args   = "'Node n#{i} has been built'"
      end
    end
  }
end
